<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>boat_bringup</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="leo@todo.todo">leo</maintainer>
  <license>TODO: License declaration</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>boat_description</exec_depend>
  <exec_depend>unitree_lidar_ros2</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <exec_depend>boat_perception</exec_depend>
  <exec_depend>boat_mission</exec_depend>
  <exec_depend>boat_control</exec_depend>
  <exec_depend>boat_vehicle</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
  <exec_depend>boat_dashboard</exec_depend>
</package>
